#!/bin/sh

urxvtd &

start-pulseaudio-x11 &

autocutsel -fork

tinymount &

dropbox &

source /etc/X11/reload_services.sh

parcellite &

nm-applet &

blueman-applet &


if [ -x /usr/bin/gpg-agent ]; then
  eval "$(/usr/bin/gpg-agent --daemon)"
fi
if [ -x /usr/bin/ssh-agent ]; then
  eval "$(/usr/bin/ssh-agent -s)"
fi

/usr/bin/xmonad

