#!/bin/sh


ASTAH_HOME="/usr/local/opt/astah"
ASTAH_JAR="astah-pro.jar"

CLASSPATH=${ASTAH_HOME}/${ASTAH_JAR}

JAVA_OPTS="-Xms16m -Xmx384m"

java ${JAVA_OPTS} -jar ${ASTAH_HOME}/${ASTAH_JAR} $1 $2 $3

